export const cities = [
  {
    name: "New York",
    latitude: 40.7128,
    longitude: -74.006,
    "long-name": "New York City",
    "short-name": "NYC",
  },
  {
    name: "London",
    latitude: 51.5074,
    longitude: -0.1278,
    "long-name": "Greater London",
    "short-name": "LON",
  },
  {
    name: "Paris",
    latitude: 48.8566,
    longitude: 2.3522,
    "long-name": "Paris, Île-de-France",
    "short-name": "PAR",
  },
  {
    name: "Tokyo",
    latitude: 35.6762,
    longitude: 139.6503,
    "long-name": "Tokyo, Kanto",
    "short-name": "TKY",
  },
  {
    name: "Los Angeles",
    latitude: 34.0522,
    longitude: -118.2437,
    "long-name": "Los Angeles County",
    "short-name": "LA",
  },
  {
    name: "Sydney",
    latitude: -33.8651,
    longitude: 151.2094,
    "long-name": "Sydney, New South Wales",
    "short-name": "SYD",
  },
  {
    name: "Hong Kong",
    latitude: 22.3193,
    longitude: 114.1694,
    "long-name": "Hong Kong Special Administrative Region",
    "short-name": "HKG",
  },
  {
    name: "Dubai",
    latitude: 25.2048,
    longitude: 55.2708,
    "long-name": "Dubai, Emirate of Dubai",
    "short-name": "DXB",
  },
  {
    name: "Rio de Janeiro",
    latitude: -22.9068,
    longitude: -43.1729,
    "long-name": "Rio de Janeiro, Rio de Janeiro State",
    "short-name": "RIO",
  },
  {
    name: "Bangkok",
    latitude: 13.7563,
    longitude: 100.5018,
    "long-name": "Bangkok, Krung Thep Maha Nakhon",
    "short-name": "BKK",
  },
  {
    name: "Barcelona",
    latitude: 41.3851,
    longitude: 2.1734,
    "long-name": "Barcelona, Catalonia",
    "short-name": "BCN",
  },
  {
    name: "Moscow",
    latitude: 55.7558,
    longitude: 37.6173,
    "long-name": "Moscow, Moscow Oblast",
    "short-name": "MOW",
  },
  {
    name: "Cairo",
    latitude: 30.0444,
    longitude: 31.2357,
    "long-name": "Cairo Governorate",
    "short-name": "CAI",
  },
  {
    name: "São Paulo",
    latitude: -23.5505,
    longitude: -46.6333,
    "long-name": "São Paulo, São Paulo State",
    "short-name": "SAO",
  },
  {
    name: "Toronto",
    latitude: 43.6532,
    longitude: -79.3832,
    "long-name": "Toronto, Ontario",
    "short-name": "TOR",
  },
  {
    name: "Berlin",
    latitude: 52.52,
    longitude: 13.405,
    "long-name": "Berlin, Berlin State",
    "short-name": "BER",
  },
  {
    name: "Mumbai",
    latitude: 19.076,
    longitude: 72.8777,
    "long-name": "Mumbai, Maharashtra",
    "short-name": "BOM",
  },
  {
    name: "Amsterdam",
    latitude: 52.3667,
    longitude: 4.8945,
    "long-name": "Amsterdam, North Holland",
    "short-name": "AMS",
  },
  {
    name: "Seoul",
    latitude: 37.5665,
    longitude: 126.978,
    "long-name": "Seoul, Seoul Capital Area",
    "short-name": "SEL",
  },
  {
    name: "Istanbul",
    latitude: 41.0082,
    longitude: 28.9784,
    "long-name": "Istanbul, Istanbul Province",
    "short-name": "IST",
  },
];
